### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by Ashik20025** [nerajbobra/lstm-cnn-eeg-sleep-staging#2]
In training module, getting this issue FileNotFoundError: [Errno 2] No such file or directory: 'X_train_spec.pkl' and also spectrogram generation taking more time and getting tensorflow issue also

**Comment by nerajbobra** [comment]
Hi, you have to run gen_spectrogram.ipynb to get the X_train_spec.pkl file. Unfortunately I didn't make note of which tensorflow version I used, but I would suggest trying 2.5.0 or less. Hope it helps

**Comment by Ashik20025** [comment]
I am not able to use tensorflow version less than 2.5.0 currently it is not
available
Can you suggest me a way
