### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by Ashik20025** [nerajbobra/lstm-cnn-eeg-sleep-staging#3]
I'm having trouble finding TensorFlow versions earlier than 2.5.0. I've attempted various methods, but they aren't working. Any suggestions on how to resolve this?

**Comment by proxOP** [comment]
try :
pip install tensorflow==2.13.0

Or instead of using 2.13.0 you can choose  (from versions: 2.12.0rc0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0, 2.14.1, 2.15.0rc0, 2.15.0rc1, 2.15.0)
